name: project_achasan
description: A new Flutter project.
publish_to: 'none'
version: 2.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  supabase_flutter: ^2.12.4
  flutter_map: ^8.3.0
  latlong2: ^0.9.1
  geolocator: ^14.0.2
  provider: ^6.0.5
  intl: ^0.18.1
  google_fonts: ^8.1.0
  glassmorphism: ^3.0.0
  http: ^1.6.0
  flutter_dotenv: ^5.1.0
  google_generative_ai: ^0.4.3
  pedometer: ^4.0.1
  permission_handler: ^11.3.0
  shared_preferences: ^2.5.2
  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.2
  package_info_plus: ^8.0.0
  connectivity_plus: ^7.1.1
  shorebird_code_push: ^2.0.6
  lucide_icons_flutter: ^3.1.14+2
  showcaseview: ^5.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7

flutter:
  assets:
    - .env
    - shorebird.yaml
    - assets/images/
    - assets/data/
  uses-material-design: true
